// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package ro.andonescu.demos.springmvcfreemarker.webforms;

import java.util.Date;

public class RegistrationFormBuilder extends RegistrationFormBuilderBase<RegistrationFormBuilder> {
    public static RegistrationFormBuilder registrationForm() {
        return new RegistrationFormBuilder();
    }

    public RegistrationFormBuilder() {
        super(new RegistrationForm());
    }

    public RegistrationForm build() {
        return getInstance();
    }
}

class RegistrationFormBuilderBase<GeneratorT extends RegistrationFormBuilderBase<GeneratorT>> {
    private RegistrationForm instance;

    protected RegistrationFormBuilderBase(RegistrationForm aInstance) {
        instance = aInstance;
    }

    protected RegistrationForm getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withEmail(String aValue) {
        instance.setEmail(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPassword(String aValue) {
        instance.setPassword(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPasswordConf(String aValue) {
        instance.setPasswordConf(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLastName(String aValue) {
        instance.setLastName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withFirstName(String aValue) {
        instance.setFirstName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withBirthDate(Date aValue) {
        instance.setBirthDate(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAddress(String aValue) {
        instance.setAddress(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCity(String aValue) {
        instance.setCity(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCounty(String aValue) {
        instance.setCounty(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAgreement(Boolean aValue) {
        instance.setAgreement(aValue);

        return (GeneratorT) this;
    }
}
